### ISSUE TITLE
Requirements 1.1.3.3.5. - Photo Tagging Events

### ISSUE THREAD

**Issue by dkilyas** [bounswe/bounswe2018group9#88] opened 2018-03-15 09:31 UTC
I was doing web mockups and one of our requirements was not clear. The requirement :
    - 1.1.3.3.5. Users shall be able to post photos by tagging certain events.
Our app is based on events. The thing that is not clear is the place of the photos shared. if we clearify, how they are going to share photos and where to put them, then the problem will be solved. Are the photos shared going to be put on the feed page or another place or are we not going to allow sharing photos? If another place, where we put them any ideas?

**Comment by dkilyas** [comment] 2018-03-15 20:58
Thank you for your feedback @gumityolcu. I added share picture button so that the user can share photos about event. The photos will be seen on the fully detailed page of the events and the profile pages of the user who shared the photo.

**Comment by okyksl** [comment] 2018-03-17 08:52
@gumityolcu I believe you described situation perfectly. 

* @gumityolcu @serkan-ozel-2015400123 may I ask is this a _must do_ requirement i.e **shall** or is this a **should** requirement? I think it is a **should** requirement.
* @serkan-ozel-2015400123 do we cover the cases @gumityolcu described in the requirements?

**Comment by serkan-ozel-2015400123** [comment] 2018-03-17 20:31
@okyksl  @gumityolcu Actually, there are more specifications in @gumityolcu's ideas. We can add them but:
the photos should be added from an event details page. -- this means annotations i think
the photos should be viewable from event pages and profile pages -- it is viewable from event pages of course, but normally there is no feature of adding photos to profile page. I can add this to requirements if it is not there.
Now, because photos are viewable in the event page, they can be seen in the trending page -- I think we should only show original event photos in feed , not added photos

**Comment by serkan-ozel-2015400123** [comment] 2018-03-17 20:32
@okyksl "may I ask is this a must do requirement i.e shall or is this a should requirement? I think it is a should requirement. "
I remeber that I didnt write this requirement so we can decide now.

**Comment by okyksl** [comment] 2018-03-18 15:43
@serkan-ozel-2015400123 I believe @gumityolcu meant _Timeline_ page instead of _Profile_ page. I actually think **1.1.3.3.5.** is clear enough, it describes the situation where user post an picture related with an event (with a certain tag to refer the event) _on her profile_. Couple of things to resolve:

* First of all, do we have specific tags for events?
* If we are going to have a tag-like structure to refer events, does these referrals from user timelines to events will accumulate under the event page?
* Does annotations cover cases where user shares an individual information or is it only about information about the event itself? 

@gumityolcu wrote:

> the photos should be added from an event details page.

I believe @gumityolcu thinks that instead of posting pictures related with an event from _Timeline_ page, users should post pictures related with an event from that _Event_ page. I think we can resolve these both ideas by enabling both features at the same time.

@gumityolcu could you clarify things a bit for us?

**Comment by gumityolcu** [comment] 2018-03-18 17:20
@okyksl @serkan-ozel-2015400123 @dkilyas Guys, what I wrote was what I assumed, what I had in mind, I didn't mean to say that these are what our requirements say.

- I checked the project description document and the customer meeting, there is no word of adding photos to events or by tagging events. Therefore it is up to us to decide whether this is a should or shall requirement. I also think it should be a shall requirement.

- As to where is the proper place for the user to put photos about an event : 

While reflecting over this subject I **assume**:
1.  A photo must be associated with exactly one event
2. A user can only post photos about an event that they have participated.

I think the first assumption is important in order for us to define the boundaries of our platform : This is a platform about cultural activities, thus the first assumption. The second, I think, is just logical.

So, I believe event details page makes sense because each photo should associated to exactly one event. I mean, if we don't let the user put a photo without referring to an event why not associate photos with event pages? Furthermore, since the events that a user has participated in -which are the only events that the user can post a photo about- will be listed in the users timeline, it will not be very hard to reach the page and add a photo.

I believe implementing a tagging system for events is hard for us to program and hard for the users to understand and use. Actually, -I don't know the technical term for this- we can add this option to the event summary (the component that shows initial information about an event in the feed/trending/timeline pages). This would let the user to add photos from her profile without having to select a proper tag for the event. The user opens her timeline, where there is a "Post photo" option for each of the events that she has attended, and simply taps the button without having to choose the proper event from a list or having to select a tag.

I think this can be discussed tomorrow in the meeting.

**Comment by nazmicancalik** [comment] 2018-03-18 20:05
@gumityolcu @okyksl @dkilyas @serkan-ozel-2015400123 Guys, here is what I thought about photos and tags:

* Do we have to manage photos if they are not included in the user requirements that are given to us by our customer ?
* If we are to manage photos I think  that @gumityolcu is right. Every photo must be an item of an event. So, imo there shouldn't  be such thing as photos of a user. There must only be photos of events. And photos can have an author or publisher field for future use. But I don't think that it is necessary to show a specific photo portfolio like instagram for each user.

* For tagging, as far as I am concerned, every event has tags and tags should have a finger in the  pie when determining recommendations. I haven't understand actually what is the problem here. We can talk it in this week's meeting

**Comment by byklyci** [comment] 2018-04-02 16:36
If the issue is done, please close it.Thanks for your effort.

**Closed** 2018-05-16 13:28 UTC
Labels: Priority: Medium, Status: Help Needed
