### ISSUE TITLE
Use Case Diagrams

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#102] opened 2018-03-31 18:26 UTC
Guys me and @akaogluozgur are working on Use case diagrams it will be ready tomorrow afternoon

**Comment by nazmicancalik** [comment] 2018-04-01 14:55
Guys @akaogluozgur and I have made a somewhat final use case diagram. Here how it looks like:
![actopus](https://user-images.githubusercontent.com/25107149/38174438-a826b8b0-35d5-11e8-9095-b07b0dfe0081.png)

Ps: Tonight with the additon of @okyksl we will finalize the use case diagram and  put it on wiki page.

**Comment by okyksl** [comment] 2018-04-01 19:30
Great work as usual @nazmicancalik @akaogluozgur!

**Comment by akaogluozgur** [comment] 2018-04-01 21:39
The diagram is added our wiki page, [Use Case Diagrams](https://github.com/bounswe/bounswe2018group9/wiki/Use-Case-Diagrams)

**Comment by byklyci** [comment] 2018-04-02 16:36
If the issue is done, please close it.Thanks for your effort.

**Closed** 2018-04-02 18:46 UTC
Labels: Platform: Documentation, Priority: Medium
