### ISSUE TITLE
Sequence Diagrams Team Sync

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#91] opened 2018-03-24 08:18 UTC
Guys, can everyone give a feedback for the sequence diagrams creation.
* If you are working on sequence diagrams, could you gave a list of which ones you created or will create ?

That way we can sync and not do a redundant work. 
I guess Kemal and Didem have already created some of them, so could you guys share it here too :D Please refer to @gkhntkl ' s issue for sequence diagrams to create from [here](https://github.com/bounswe/bounswe2018group9/issues/86)

**Comment by gumityolcu** [comment] 2018-03-24 19:33
I think you can edit this comment. If so, please feel free to edit it and add as you contribute.

**Diagrams that are done :** 

- Sign In
- Sign Up
- Create Event
- Search Event
- Recommendation

**Diagrams currently being done**:

- Feed
- Trending

**Comment by okyksl** [comment] 2018-03-25 00:02
@bounswe/bounswe2018group9 could we please clarify this so that we can track our progress and also update `Project Plan` with the necessary details?

**Comment by serkan-ozel-2015400123** [comment] 2018-03-25 03:54
Actually I am not being able to draw profile sequence diagrams precisely because of ambiguity of classes or methods. My drawings so far : ![]*https://www.dropbox.com/s/0n5o300fpyw5mb5/20180325_065052.jpg?dl=0)

**Comment by gumityolcu** [comment] 2018-03-25 13:10
Hey folks, I added the links to my comment. It would be much appreciated if you added the links to the diagrams that you prepared

**Comment by serkan-ozel-2015400123** [comment] 2018-03-25 15:11
I need someone to review my diagrams and draw it in lucidchart? 
https://www.dropbox.com/s/0n5o300fpyw5mb5/20180325_065052.jpg?dl=0

**Comment by serkan-ozel-2015400123** [comment] 2018-03-25 17:33
Also, timeline and edit profile left.

**Comment by didemongu** [comment] 2018-03-25 18:17
I will draw your diagrams in lucidchart @serkan-ozel-2015400123

**Comment by byklyci** [comment] 2018-04-02 16:36
If the issue is done, please close it.Thanks for your effort.

**Comment by okyksl** [comment] 2018-05-17 10:17
I'm closing this issue since it's been inactive for a long period.

**Closed by okyksl** 2018-05-17 10:17 UTC
Labels: Platform: Documentation, Priority: Critical
