### ISSUE TITLE
Review Meeting Notes for Week 6

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#83] opened 2018-03-13 09:02 UTC
Let's review the meeting notes for [Week 6](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%236-(12.03.2018)). I believe that there would be missing points not included or some of the points might be misunderstood. We can correct them together.

* After you read the notes, feel free to make necessary changes, also mention them here.

Check the box after you read the notes.

* [x] Gökhan Tekel
* [x] Didem Öngü
* [x] Hamdi Özgür Akaoğlu
* [x] Nazmican Çalık
* [ ] İlyas Demirkıran
* [x] Yusuf Kalaycı
* [x]  Serkan Özel
* [x] Kemal Tulum
* [x] Galip Ümit Yolcu
* [ ] Oğuz Kaan Yüksel

**Comment by nazmicancalik** [comment] 2018-03-13 09:30
@kemaltulum I have reviewed the meeting notes and added my status update. Since I have finished with android mockups, I can help @akaogluozgur @byklyci in `Class Diagrams`.

**Comment by gumityolcu** [comment] 2018-03-13 17:08
Great work thanks.

**Comment by akaogluozgur** [comment] 2018-03-13 19:27
@nazmicancalik sure bro, An issue will be opened until tomorrow so we can collaborate from there.

**Comment by okyksl** [comment] 2018-03-15 05:55
@bounswe/bounswe2018group9 initial plan of my for `Status` section was to review the previous meeting at the _beginning of the next meeting all together_. I see that some of us started to fill [Meeting #6 Status](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%236-(12.03.2018)#5-status). The question is, whether should we:
* Only fill the [Workload](https://github.com/bounswe/bounswe2018group9/wiki/Worklog), and do not touch `Status` section. By doing so, we can all fill it together in the meetings to catch up the **status** of the group and the project.
* Fill both [Workload](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) and `Status` section throughout the week. However, I think its redundant to fill two things for resource usage and also its harder to manage the consistency if all of us edit both of them simultaneously.

**Comment by okyksl** [comment] 2018-03-16 22:35
@bounswe/bounswe2018group9 could you all please read the concerns I wrote above this post?

Look at these two files:
* [Meeting #6 Status](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%236-(12.03.2018)#5-status)
* [Worklog Week #6](https://github.com/bounswe/bounswe2018group9/wiki/Worklog#week-6)

There are already inconsistencies among these files, we are missing some reports on [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog).

**Please bear in mind the following**:
* **Don't edit** `Meeting Status` section expect meeting times.
* Enter your work to the [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) with _task id, log and duration_.

**Comment by byklyci** [comment] 2018-04-02 16:35
If the issue is done, please close it.Thanks for your effort.

**Closed** 2018-04-11 23:33 UTC
Labels: Platform: Documentation, Priority: Critical, Status: Accepted, Status: Help Needed, Type: Enhancement
